-- Checks if the account with the AC_ID and CA_ID exists in the Accounts table.
create or replace FUNCTION FN_ACCOUNT_EXISTS(SOURCE IN TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ID_T)
RETURN BOOLEAN IS
ENT_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO ENT_COUNT FROM "Account" a WHERE a.AC_ID = SOURCE.AC_ID AND a.CA_ID=SOURCE.CA_ID;
  IF ENT_COUNT = 0 THEN
    RETURN FALSE;
  ELSE
    RETURN TRUE;
  END IF;
END FN_ACCOUNT_EXISTS;