-- Checks if a child of a parent account exists in the Account table.
create or replace FUNCTION FN_CHILD_ACCOUNT_EXISTS(SOURCE IN TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ID_T)
RETURN BOOLEAN IS
ENT_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO ENT_COUNT FROM "Account" a WHERE a.AC_ID LIKE (SOURCE.AC_ID || '_') AND a.CA_ID=SOURCE.CA_ID;
  IF ENT_COUNT = 0 THEN
    RETURN FALSE;
  ELSE
    RETURN TRUE;
  END IF;
END FN_CHILD_ACCOUNT_EXISTS;