create or replace FUNCTION FN_TABLE_HAS_INDEX 
(IN_TABLE IN PR_INCOME_STATMENT_PACKAGE.STATMENTS_T, IN_INDEX IN VARCHAR2) RETURN BOOLEAN AS 
STATMENT PR_INCOME_STATMENT_PACKAGE.STATMENT_T;
BEGIN
  STATMENT := IN_TABLE(IN_INDEX);
  RETURN TRUE;
EXCEPTION
WHEN OTHERS THEN
   RETURN FALSE;
END FN_TABLE_HAS_INDEX;