create or replace PROCEDURE PR_GENERAL_LEDGER (
  BUSINESS_ID IN "Business".BS_ID%TYPE,
  REPORT OUT PR_GL_PACKAGE.GL_T) AS

CA_ARRAY PR_GL_PACKAGE.CA_ARRAY_T;
AC_ARRAY PR_GL_PACKAGE.AC_ARRAY_T;
VE_ARRAY PR_GL_PACKAGE.VE_ARRAY_T;

TEMP "Vaucher Entry".JVE_DEBITS%TYPE;

PAGE PR_GL_PACKAGE.GL_PAGE_T;

BEGIN
  
  SELECT bhc.CA_ID BULK COLLECT INTO CA_ARRAY FROM "BS Has COA" bhc WHERE bhc.BS_ID=BUSINESS_ID;
  
  FOR idx in 1..CA_ARRAY.COUNT LOOP
  
    SELECT * BULK COLLECT INTO AC_ARRAY FROM "Account" a WHERE a.CA_ID=CA_ARRAY(idx);
    
    FOR jdx in 1..AC_ARRAY.COUNT LOOP

      REPORT(AC_ARRAY(jdx).AC_ID).ACC := AC_ARRAY(jdx);
      
      SELECT * BULK COLLECT INTO VE_ARRAY FROM "Vaucher Entry" v WHERE v.CA_ID=CA_ARRAY(idx) and v.AC_ID=AC_ARRAY(jdx).AC_ID;
      
      REPORT(AC_ARRAY(jdx).AC_ID).VE := PR_GL_PACKAGE.FN_MERGE_JVE(REPORT(AC_ARRAY(jdx).AC_ID).VE, VE_ARRAY);
    
    END LOOP;
  
  END LOOP;
  
  SELECT * BULK COLLECT INTO AC_ARRAY FROM "Account" a WHERE a.CA_ID in (SELECT bhc.CA_ID FROM "BS Has COA" bhc WHERE bhc.BS_ID=BUSINESS_ID);
  
  FOR idx in 1..AC_ARRAY.COUNT LOOP

    TEMP := 0;
  
    FOR kdx in 1..REPORT(AC_ARRAY(idx).AC_ID).VE.COUNT LOOP
    
      TEMP := TEMP + REPORT(AC_ARRAY(idx).AC_ID).VE(kdx).JVE_DEBITS - REPORT(AC_ARRAY(idx).AC_ID).VE(kdx).JVE_CREDITS;
      REPORT(AC_ARRAY(idx).AC_ID).BA(kdx) := TEMP;
    
    END LOOP;
  
  END LOOP;
  
END PR_GENERAL_LEDGER;