CREATE OR REPLACE 
PACKAGE PR_INCOME_STATMENT_PACKAGE AS 

TYPE VE_T IS TABLE OF "Vaucher Entry"%ROWTYPE INDEX BY BINARY_INTEGER;

TYPE STATMENT_T IS RECORD (CA_ID "Account".CA_ID%TYPE,AC_ID "Account".AC_ID%TYPE,TOTAL "Vaucher Entry".JVE_DEBITS%TYPE);
TYPE STATMENTS_T IS TABLE OF STATMENT_T INDEX BY VARCHAR(3);

TYPE INCOME_STATMENT_T IS RECORD (income STATMENTS_T, loses STATMENTS_T, income_subtotal "Vaucher Entry".JVE_DEBITS%TYPE, loses_subtotal "Vaucher Entry".JVE_DEBITS%TYPE);

END PR_INCOME_STATMENT_PACKAGE;