CREATE OR REPLACE PROCEDURE PR_INCOME_STATMENT
(BUSINESS_ID IN "Business".BS_ID%TYPE) AS 

INCOME_STATMENT PR_INCOME_STATMENT_PACKAGE.INCOME_STATMENT_T;
VAUCHER_ENTRIES PR_INCOME_STATMENT_PACKAGE.VE_T;

TEMP PR_INCOME_STATMENT_PACKAGE.STATMENT_T;

BEGIN
  
  SELECT v.JVE_ID, v.JV_ID, v.SUG_ID, v.VET_ID, v.BS_ID, v.CA_ID, v.AC_ID, v.JVE_DESCRIPTION, v.JVE_DEBITS, v.JVE_CREDITS 
         BULK COLLECT INTO VAUCHER_ENTRIES
         FROM "Vaucher Entry" v, "BS Has COA" bhc
         WHERE v.CA_ID=bhc.CA_ID and bhc.BS_ID=BUSINESS_ID;

  INCOME_STATMENT.income_subtotal := 0;
  INCOME_STATMENT.loses_subtotal := 0;
  
  FOR idx in 1..VAUCHER_ENTRIES.COUNT LOOP
  
    IF SUBSTR(VAUCHER_ENTRIES(idx).AC_ID, 1 , 1) = '5' THEN
      
      IF FN_TABLE_HAS_INDEX(INCOME_STATMENT.INCOME, VAUCHER_ENTRIES(idx).AC_ID) THEN
        INCOME_STATMENT.INCOME(VAUCHER_ENTRIES(idx).AC_ID).TOTAL := INCOME_STATMENT.INCOME(VAUCHER_ENTRIES(idx).AC_ID).TOTAL + (VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS);
      ELSE
        INCOME_STATMENT.INCOME(VAUCHER_ENTRIES(idx).AC_ID).AC_ID := VAUCHER_ENTRIES(idx).AC_ID;
        INCOME_STATMENT.INCOME(VAUCHER_ENTRIES(idx).AC_ID).CA_ID := VAUCHER_ENTRIES(idx).CA_ID;
        INCOME_STATMENT.INCOME(VAUCHER_ENTRIES(idx).AC_ID).TOTAL := VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS;
      END IF;
      
      INCOME_STATMENT.income_subtotal := INCOME_STATMENT.income_subtotal + (VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS);
    
    ELSIF SUBSTR(VAUCHER_ENTRIES(idx).AC_ID, 1 , 1) = '6' THEN
      IF FN_TABLE_HAS_INDEX(INCOME_STATMENT.LOSES, VAUCHER_ENTRIES(idx).AC_ID) THEN
        INCOME_STATMENT.LOSES(VAUCHER_ENTRIES(idx).AC_ID).TOTAL := INCOME_STATMENT.LOSES(VAUCHER_ENTRIES(idx).AC_ID).TOTAL + (VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS);
      ELSE
        INCOME_STATMENT.LOSES(VAUCHER_ENTRIES(idx).AC_ID).AC_ID := VAUCHER_ENTRIES(idx).AC_ID;
        INCOME_STATMENT.LOSES(VAUCHER_ENTRIES(idx).AC_ID).CA_ID := VAUCHER_ENTRIES(idx).CA_ID;
        INCOME_STATMENT.LOSES(VAUCHER_ENTRIES(idx).AC_ID).TOTAL := VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS;
      END IF;
      
      INCOME_STATMENT.loses_subtotal := INCOME_STATMENT.loses_subtotal + (VAUCHER_ENTRIES(idx).JVE_CREDITS-VAUCHER_ENTRIES(idx).JVE_DEBITS);
    
    END IF;
  END LOOP;
  
END PR_INCOME_STATMENT;