DECLARE

ADDITION PR_NEXT_YEAR_PACKAGE.ACCOUNTS_T;
DELITION PR_NEXT_YEAR_PACKAGE.ACCOUNTS_T;
SRC_CA_ID "Chart of Accounts".CA_ID%TYPE;
DST_CA_ID "Chart of Accounts".CA_ID%TYPE;

CA_ID_DEST NUMBER := 9;
CA_ID_SRC NUMBER := 1;

BEGIN

ADDITION(1).CA_ID := CA_ID_DEST;
ADDITION(1).AC_ID := '29';
ADDITION(1).AC_NAME := 'AC 1';

ADDITION(2).CA_ID := CA_ID_DEST;
ADDITION(2).AC_ID := '28';
ADDITION(2).AC_NAME := 'AC 2';

ADDITION(3).CA_ID := CA_ID_DEST;
ADDITION(3).AC_ID := '27';
ADDITION(3).AC_NAME := 'AC 3';


DELITION(1).CA_ID := CA_ID_DEST;
DELITION(1).AC_ID := '01';
DELITION(1).AC_NAME := 'asd';

PR_NEXT_YAER_COPY(ADDITION, DELITION, CA_ID_SRC, CA_ID_DEST);

END;