create or replace PACKAGE TG_PARENT_ACCOUNT_PACKAGE IS


TYPE ACCOUNT_ID_T IS RECORD (AC_ID "Account".AC_ID%TYPE, CA_ID "Account".CA_ID%TYPE);
TYPE ACCOUNT_ARRAY_T IS TABLE OF ACCOUNT_ID_T INDEX BY BINARY_INTEGER;

ACCOUNT_ARRAY ACCOUNT_ARRAY_T;
ACCOUNT_ARRAY_COUNT NUMBER(4) := 0;

PARENT_ARRAY ACCOUNT_ARRAY_T;
PARENT_ARRAY_COUNT NUMBER(4) := 0;

VE_ACC_FK_UPDATE_ENABLED BOOLEAN := TRUE;

END TG_PARENT_ACCOUNT_PACKAGE;