create or replace TRIGGER TG_ST_PARENT_ACCOUNT_BEFORE 
BEFORE INSERT OR UPDATE OR DELETE OF AC_ID ON "Account" 
BEGIN
  TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ARRAY.DELETE;
  TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ARRAY_COUNT := 0;
  
  TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY.DELETE;
  TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY_COUNT := 0;
END;