create or replace TRIGGER TG_ST_PARENT_ACCOUNT_AFTER 
AFTER INSERT OR UPDATE OR DELETE OF AC_ID ON "Account" 
DECLARE
EXIST_V NUMBER(1);
BEGIN

  FOR i in 1..TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ARRAY_COUNT LOOP
    IF NOT(FN_ACCOUNT_EXISTS(TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ARRAY(i))) THEN
      Raise_Application_Error(-20000, 'A parent must exist');
    END IF;
  END LOOP;
  
  FOR i in 1..TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY_COUNT LOOP
  
    IF FN_CHILD_ACCOUNT_EXISTS(TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY(i)) THEN
      Raise_Application_Error(-20000, 'A child account exists!');
    END IF;
  END LOOP;
    
END;