create or replace PACKAGE PR_GL_PACKAGE AS 

TYPE CA_ARRAY_T IS TABLE OF "Vaucher Entry".CA_ID%TYPE INDEX BY BINARY_INTEGER;

TYPE AC_ARRAY_T IS TABLE OF "Account" % rowtype INDEX BY BINARY_INTEGER;

TYPE VE_ARRAY_T IS TABLE OF "Vaucher Entry"%rowtype INDEX BY BINARY_INTEGER;
TYPE BA_ARRAY_T IS TABLE OF "Vaucher Entry".JVE_DEBITS%TYPE INDEX BY BINARY_INTEGER;

TYPE GL_PAGE_T IS RECORD (acc "Account" % rowtype, ve VE_ARRAY_T, ba BA_ARRAY_T);

TYPE GL_T IS TABLE OF GL_PAGE_T INDEX BY VARCHAR(3);

FUNCTION FN_MERGE_JVE (q IN VE_ARRAY_T, w IN VE_ARRAY_T) RETURN VE_ARRAY_T; 

END PR_GL_PACKAGE;