create or replace TRIGGER TG_MERGE_DELETED_ACCOUNT 
BEFORE DELETE ON "Account" FOR EACH ROW
DECLARE
SRC TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ID_T;
TRG TG_PARENT_ACCOUNT_PACKAGE.ACCOUNT_ID_T;
BEGIN

  SRC.AC_ID := :OLD.AC_ID;
  SRC.CA_ID := :OLD.CA_ID;

  IF (LENGTH(:OLD.AC_ID) = 3) THEN

    TRG.AC_ID := SUBSTR(:OLD.AC_ID, 1, 2);
    TRG.CA_ID := :OLD.CA_ID;
  
    TG_PARENT_ACCOUNT_PACKAGE.VE_ACC_FK_UPDATE_ENABLED := FALSE;
    PR_MAIN_PACKAGE.PR_REWIRE_JOURNAL_VAUCHER(SRC, TRG);
    PR_MAIN_PACKAGE.PR_REWIRE_JVT(SRC, TRG);
    TG_PARENT_ACCOUNT_PACKAGE.VE_ACC_FK_UPDATE_ENABLED := TRUE;
  
  ELSIF (LENGTH(:OLD.AC_ID) = 2) THEN
  
    
    TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY_COUNT := TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY_COUNT + 1;
    TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY(TG_PARENT_ACCOUNT_PACKAGE.PARENT_ARRAY_COUNT) := SRC;

  END IF;

  
  IF PR_MAIN_PACKAGE.FN_ENTRY_EXISTS(SRC) OR PR_MAIN_PACKAGE.FN_JVT_ENTRY_EXISTS(SRC) THEN
    Raise_Application_Error(-20000, 'This account is referenced!');
  END IF;

END;